### ISSUE TITLE
Добавить хук usePopout

### ISSUE THREAD

**Issue by vladyoslav** [cteamdev/router#7]
Добавить хук usePopout, реализующий методы setPopout и closePopout. Такой хук позволит легко подключить отображение попаутов к истории переходов.

**Comment by kosheeta** [comment]
Для реализации попаутов, как и модалок, необходимо использовать хук useParams с параметрами, например, `modal` и `popout`. Реализовано в роутере не будет - подробнее в #5.

**Comment by kosheeta** [comment]
Я подумал и решил, что всё-таки неплохо было бы такое реализовать.

**Comment by kosheeta** [comment]
Вместо хука `usePopout` добавлен `PopoutRoot`.
